services:
  # --- Infrastructure ---
  db:
    image: cockroachdb/cockroach:v23.1.10
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./data/cockroach-data:/cockroach/cockroach-data

  kafka:
    image: apache/kafka:4.2.0
    ports:
      - "9092:9092"

  gateway:
    image: envoyproxy/envoy:v1.26-latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "80:10000"
      - "9901:9901"

  # --- Microservices ---
  order-service:
    build: ./microservices/order-service
    depends_on:
      - db
      - kafka
    environment:
      - DB_URL=postgresql://root@db:26257/defaultdb?sslmode=disable
      - KAFKA_BROKERS=kafka:9092

  user-service:
    build: ./microservices/user-service
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://root@db:26257/defaultdb?sslmode=disable

  notification-service:
    build: ./microservices/notification-service
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
